
import { useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import ProgressBar from './ProgressBar';
import PremiumBanner from './PremiumBanner';
import useAuth from '@/hooks/useAuth';

export default function PostForm({ onPostGenerated }: { onPostGenerated: (post: any) => void }) {
  const { user } = useAuth();
  const [isLoading, setIsLoading] = useState(false);
  const [topic, setTopic] = useState('');
  const [tone, setTone] = useState('Professional');
  const [style, setStyle] = useState('Storytelling');

  const tones = [
    'Professional', 'Casual', 'Inspirational', 'Informative', 'Persuasive'
  ];

  const styles = [
    'Storytelling', 'Listicle', 'How-to', 'Opinion', 'Case Study', 'News Update'
  ];

  const isLimitReached = 
    user?.role === 'free' && 
    (user?.postCount || 0) >= 20;

  const generatePost = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!topic) {
      toast.error('Please enter a topic');
      return;
    }

    try {
      setIsLoading(true);
      // In a real app, this would call your API
      // For demo purposes, we'll create a mock post
      setTimeout(() => {
        const mockPost = {
          id: `post-${Math.random().toString(36).substr(2, 9)}`,
          topic,
          tone,
          style,
          content: `This is a simulated LinkedIn post about "${topic}" in a ${tone} tone using ${style} style. In a real app, this would be generated by an AI service.`,
          createdAt: new Date().toISOString()
        };
        
        onPostGenerated(mockPost);
        toast.success('Post generated successfully!');
        setIsLoading(false);
      }, 1500);
    } catch (error: any) {
      toast.error(error.message || 'Failed to generate post');
      setIsLoading(false);
    }
  };

  return (
    <Card className="w-full">
      <CardContent className="p-6">
        {user?.role !== 'premium' && (
          <ProgressBar className="mb-4" />
        )}
        
        <form onSubmit={generatePost} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="topic">Topic</Label>
            <Input
              id="topic"
              placeholder="e.g., Remote work productivity tips"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              disabled={isLoading || isLimitReached}
            />
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="tone">Tone</Label>
              <Select 
                value={tone} 
                onValueChange={setTone}
                disabled={isLoading || isLimitReached}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select tone" />
                </SelectTrigger>
                <SelectContent>
                  {tones.map((t) => (
                    <SelectItem key={t} value={t}>{t}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="style">Style</Label>
              <Select 
                value={style} 
                onValueChange={setStyle}
                disabled={isLoading || isLimitReached}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select style" />
                </SelectTrigger>
                <SelectContent>
                  {styles.map((s) => (
                    <SelectItem key={s} value={s}>{s}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          
          <div className="pt-2">
            {isLimitReached ? (
              <PremiumBanner />
            ) : (
              <Button 
                type="submit" 
                className="w-full" 
                disabled={isLoading || !topic}
              >
                {isLoading ? 'Generating...' : 'Generate LinkedIn Post'}
              </Button>
            )}
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
